/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_polysfactory_handgesture_NativeBridge */

#ifndef _Included_com_polysfactory_handgesture_NativeBridge
#define _Included_com_polysfactory_handgesture_NativeBridge
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_polysfactory_handgesture_NativeBridge
 * Method:    nativeCreateObject
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_polysfactory_handgesture_NativeBridge_nativeCreateObject
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_polysfactory_handgesture_NativeBridge
 * Method:    nativeDestroyObject
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_polysfactory_handgesture_NativeBridge_nativeDestroyObject
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_polysfactory_handgesture_NativeBridge
 * Method:    nativeStart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_polysfactory_handgesture_NativeBridge_nativeStart
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_polysfactory_handgesture_NativeBridge
 * Method:    nativeStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_polysfactory_handgesture_NativeBridge_nativeStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_polysfactory_handgesture_NativeBridge
 * Method:    nativeProcess
 * Signature: (JJJ)V
 */
JNIEXPORT void JNICALL Java_com_polysfactory_handgesture_NativeBridge_nativeProcess
  (JNIEnv *, jclass, jlong, jlong, jlong);

/*
 * Class:     com_polysfactory_handgesture_NativeBridge
 * Method:    nativeSetSize
 * Signature: (JIIII)V
 */
JNIEXPORT void JNICALL Java_com_polysfactory_handgesture_NativeBridge_nativeSetSize
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
